### ISSUE TITLE
路径处理的问题

### ISSUE THREAD

**Issue by gtlions** [youngxhui/GinHello#1]
很不错的一个```Go Gin``` ```WEB```的入门系列，点赞点赞点赞！！！

在看到关于处理用户头像信息的相关内容是，一些处理路径的方式有不对或者错误的地方：
比如：

```
path = path + "avatar\\"
```

更正确的处理方式应该是使用```filepath.Join```:

```
path = filepath.Join(path, "avatar")
```

**Comment by youngxhui** [comment]
感谢您提出的方式，代码已更正。
