### ISSUE TITLE
访问post请求

### ISSUE THREAD

**Issue by hkhl** [youngxhui/GinHello#4]
https://github.com/youngxhui/GinHello/blob/56db3de12ddeab3f931e7d8ab52bf765094e0ab9/initRouter/initRouter.go#L25

请问这个post请求web页面怎么访问并加载页面， curl可以。
但是怎么web页面链接访问  http://localhost:8080/user/register       一直是404加载不出来

**Comment by youngxhui** [comment]
浏览器是 get 请求，所以无法访问。建议使用 curl 或者 postman 等工具进行测试。
如果在js里使用 post，请参考 ajax。
